### ISSUE TITLE
Lazy load

### ISSUE THREAD

**Issue by matyushen** [franz-josef-kaiser/Dynamic-Image-Resize#10]
Hey, great stuff, much better than using predefined image sizes with regeneration thumbnails every time. Thanks! I'm trying to add lazy load functionality to this function. Like this:

```
public function getMarkUp( $src, $hw_string, $classes ) {

    return sprintf(
        '<img src="' . get_template_directory_uri() . '/assets/img/img-placeholder.png" data-src="%s" %s%s />',
        $src,
        $hw_string,
        ! empty( $classes ) ? " class='{$classes}'" : ''
    );

}
```

But the problem that placeholder image is not being resized. How do I make it resize to the exact dimensions as the source image? Do you think it is a good practice after all?

Also, default classes and alt are missing from the output image when using this plugin(without any editing). Is that me doing something wrong?

**Comment by franz-josef-kaiser** [comment]
First off, I really appreciate if the people to which I'm talking aren't just random avatars but use some real photo, domain, etc. That makes it much easier to work with. Thanks for fixing that in advance.

Second: No idea what script is attached to that `data-src` stuff. You might want to copy/paste some mu-plugin where I can reproduce your issue. Else it's impossible (and too much work for an open source and freely available) to work on this together.

**Comment by matyushen** [comment]
Hi, I couldn't imagine that the lack of avatar could be an issue. Sorry, but what it has to do with the topic?
Speaking about your second question, it's just one of the lazy-load scripts attached to that data-src stuff ( https://github.com/luis-almeida/unveil ). But it could be any other of them, correct me if I'm wrong but does it makes any difference? I'm just trying to figure out how to resize the placeholder image ( from theme's folder ) together with the real thumbnail image using your plugin.
I also mentioned that default classes and alt are missing from the output image when using your plugin without any modifications. Do you have any ideas why that could be happening?

Thanks.

**Comment by franz-josef-kaiser** [comment]
> [...] that default classes and alt are missing from the output image

First, there's only a limited list of supported attributes, as you can see in [the `parseAttributes()`](https://github.com/franz-josef-kaiser/Dynamic-Image-Resize/blob/master/dynamic_img_resize.php#L148-L162) method. The WP core [`shortcode_atts()`](http://queryposts.com/function/shortcode_atts/) function removes everything that isn't set in the preset pairs. By now that only is 

``` #!php
array(
    'src'      => '',
    'width'    => '',
    'height'   => '',
    'classes'  => '',
    'hwmarkup' => 'true',
)
```

If you want to change that, you can write a quick mu-plugin, using the following filter inside core:

```
apply_filters( "shortcode_atts_{$shortcode}", $out, $pairs, $atts );
```

To allow that, I added the third, optional argument to the `shortcode_atts()` method, the name (`dynamic_image`). This allows targetting only this plugins shortcode and nothing else.

As the `classes` are supported, there must be a different problem. When you look at the [`sanitizeAttributes()`](https://github.com/franz-josef-kaiser/Dynamic-Image-Resize/blob/master/dynamic_img_resize.php#L169-L183) method, then one reason could be that you simply used pretty wired class names or have some other plugin or your theme influencing that. Just look [at the plugins source](https://github.com/franz-josef-kaiser/Dynamic-Image-Resize/blob/master/dynamic_img_resize.php#L241) and you will find this:

> // Let's see if the image belongs to our uploads directory…
> // …And if not: just return the image HTML string

When you look at [how the MarkUp is generated](https://github.com/franz-josef-kaiser/Dynamic-Image-Resize/blob/master/dynamic_img_resize.php#L497), then you see that there's nothing special:

```
! empty( $classes ) ? " class='{$classes}'" : ''
```

> Speaking about your second question, it's just one of the lazy-load scripts attached to that data-src stuff ( https://github.com/luis-almeida/unveil ). But it could be any other of them, correct me if I'm wrong but does it makes any difference? 

Yes, it does. I can't reproduce your issue and fishing in the dark is something no one likes doing. If you need support, the best thing you can do is to offer a developer the easiest way to actually see what you are doing and allowing her/him to get to the root of the problem as fast as possible.

> I couldn't imagine that the lack of avatar could be an issue. Sorry, but what it has to do with the topic?

Currently I'm "talking" to a random default avatar and a username that as well could be `user12345`. I don't know who you are, what you are capable off (no public repos) and on what level I need to explain stuff. That's not comfortable and using a full profile and real photo of yourself just shows attitude and the will to really talk as a person to another human. That's why I appreciate [real avatars](http://www.rarst.net/thoughts/every-door-with-kick/).

**Comment by matyushen** [comment]
I didn't mean to hide under some default avatar, I just didn't ever think of adding such. But I've just did it, especially for you :) But I'm not such developer as you, if you ask, I don't have any repos here or blog with some code-related staff. So you won't be able to background-check and decide on what level to explain stuff to me.

Probably I didn't phrase my question well. Standard classes added to thumbnails by WordPress, such as 'wp-post-image' do not appear with your plugin. But now I believe it's by design, is it? So I should add desired classes like this:

```
$post_id = get_the_ID();
$thumb_id = get_post_thumbnail_id( $post_id );
$thumb_url = wp_get_attachment_url( $thumb_id, 'full' );

echo dynamic_image_resize( 
    array( 
        'src' => $thumb_url, 
        'width' => 480, 
        'height' => 270,
        'classes' => 'wp-post-image some-custom-class'
    )
);
```

My Lazy-load plugin related question has nothing to do with that plugin itself, but about how to resize the image from theme's folder with your plugin. Lazy load plugin does simple thing - it displays placeholder image before thumbnail image gets in the viewport to increase initial page speed load. Since I'm resizing thumbnail images with your plugin I was wondering if it's possible to resize placeholder image as well.

**Comment by franz-josef-kaiser** [comment]
> Probably I didn't phrase my question well. Standard classes added to thumbnails by WordPress, such as 'wp-post-image' do not appear with your plugin. But now I believe it's by design, is it?

Yes. I wouldn't know from where to retrieve a list of core classes. If you know, please file a PR.

> Since I'm resizing thumbnail images with your plugin I was wondering if it's possible to resize placeholder image as well.

I don't know where those placeholders are. The first assumption the plugin makes is that the targetted files are (a) in the `uploads` folder (or whatever it is named via the constants) and (b) that it is available in the DB and has a `_wp_attachment_metadata` meta key that is `LIKE` the URL to the file (see source).

Summed up: I'm pretty sure that it won't work with what you are trying to do (with the lazy load plugin). You will have to craft your own logic for that. Take a look at `image_make_intermediate_size()` and the checks that I run on the result of that function. Good luck and happy coding!
