### ISSUE TITLE
filename being cut off

### ISSUE THREAD

**Issue by ghost** [franz-josef-kaiser/Dynamic-Image-Resize#12]
I'm trying to use the shortcode within PHP files, and using variables to provide the filenames. Here's an example:

<?php echo do_shortcode('[dynamic_image src="'.$gallerySet->before_img.'" width="120" height="90"]');?>

the value of $gallerySet->before-img is "/wp-content/uploads/before-after/face-lift_1_b.jpg", but when trying to view the site, the output becomes:

<img src="/wp-content/uploads/before-after/face-li" width="120" height="90">

So it looks like it's just trying to output the original file (which isn't what I believe the plugin is for. I want to be able to take a large image source, and have a resized img tag generated using the new size as the filename, rather than attributes.

Am I doing something wrong here?

UPDATE:

This is also happening when using a simple shortcode within Wordpress itself. Using the shortcode:

```
[dynamic_image src="/wp-content/uploads/before-after/face-lift_1_b.jpg" width="120" height="90" class="img-responsive"]
```

will produce the output of:

```
<img src="/wp-content/uploads/before-after/face-li" width="120" height="90">
```

**Comment by franz-josef-kaiser** [comment]
Could you please edit your question and format the code? Also there seems to be a slight misunderstanding between _GitHub_ and you and the image you added … it 404s. :)

About your URl: `/wp-content/uploads/…` is
1. interpreted as an absolute URl from your web servers root (where your uploads directory does not reside).
2. pretty strange because `before-after` is not really something that WordPress handles.
3. wrong as the `wp-content` directory is already handled [properly by the plugin](https://github.com/franz-josef-kaiser/Dynamic-Image-Resize/blob/80aecfa7765811de1f0923aae258cd16c63d8e5f/dynamic_img_resize.php#L378-L395) itself. It even takes into account having configured completely custom `wp-content/uploads` names and locations as well as it takes multisite and network installs into account.

Please take a look at how [developing and debugging is handled](https://github.com/franz-josef-kaiser/Dynamic-Image-Resize/blob/80aecfa7765811de1f0923aae258cd16c63d8e5f/dynamic_img_resize.php#L126-L141), meaning that there will not ever be any error output as long as you have debugging turned off. **ProTip:** Do not enable debugging when you have caching enabled. It could leak error messages to your customers until you flush cache. Turn cache off, turn debugging on, debug and develop and reverse the process afterwards.

Furthermore: Please do not call shortcodes by `echo`ing them like this:

``` php
<?php echo do_shortcode('[dynamic_image src="'.$gallerySet->before_img.'" width="120" height="90"]');?>
```

Just call the underlying function – shortcodes are just wrappers to call functions from within the editor. 

About your path: Your **problem** is, that you have the full path to the uploads directory in your custom object returned. You don't want and need that in nearly all cases. Just replace that part in your original object. If that is for whatever reason not possible, at least replace it in the output that you pass on:

``` php
$uploaddir = wp_upload_dir();
$imgUrl = str_replace( $uploaddir['baseurl'], "", $gallerySet->before_img );
```

_Sidenote: If that is some plugin, ask the author why s/he thinks that you need the full path to something that should get fetched dynamically and can and will be altered by filter/action callbacks._

Hope that helps. In case you have open questions, feel free to ask.
